[package]
name = "examples"
version = "0.1.0"
authors = ["martindeegan <mddeegan@gmail.com>"]

[dependencies]
rust-pigpio = { path = "../../", version = "0.1.0" }

[[bin]]
name = "light"
path = "light.rs"
